"$schema" = 'https://starship.rs/config-schema.json'

# setup format for windows
# format = """
# $directory\
# $git_branch\
# $git_status\
# $nodejs\
# $golang\
# $rust\
# $character\
# """


# setup format for mac
format = """
$directory\
$git_branch\
$git_status\
$character\
"""
right_format = """
$nodejs\
$golang\
$rust\
"""


[directory]
format = "[ $path]($style) "
style = "#4d9375"
truncation_length = 2
truncate_to_repo = true

[character]
success_symbol = "[󰙴](blue)"
error_symbol = "[󰙴](red)"

[git_branch]
format = "[󰘬 $branch ]($style)"
style = "bright-black"

[nodejs]
format = '[󰎙 $version ]($style)'
style = "yellow"

[golang]
format = '[ $version ]($style)'
style = "cyan"

[rust]
format = '[󱘗 $version ]($style)'
style = "red"